on: [push, pull_request]

env:
  NODE_VERSION: '12.x'                # set this to the node version to use

jobs:
  test-pr:
    name: Test PR
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run test --if-present
